# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-04-10 00:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voto',
            name='id',
        ),
        migrations.AlterField(
            model_name='voto',
            name='valor',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
