# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2019-04-10 13:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20190410_0015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidato',
            name='partido',
        ),
        migrations.RemoveField(
            model_name='distrito',
            name='candidato',
        ),
        migrations.RemoveField(
            model_name='distrito',
            name='voto',
        ),
        migrations.RemoveField(
            model_name='voto',
            name='valor',
        ),
        migrations.AddField(
            model_name='candidato',
            name='distrito',
            field=models.ForeignKey(default=654, on_delete=django.db.models.deletion.CASCADE, to='app.Distrito'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voto',
            name='id',
            field=models.AutoField(auto_created=True, default=54, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='voto',
            name='valido',
            field=models.BooleanField(default=True),
        ),
    ]
